public with sharing class FutureMethodeExample {
    public FutureMethodeExample(){
        Takebath();
        Tackbreakfast();
        Carservice();
        GotoOffice();
    }
   
    public void Takebath() {
        System.debug ('Takebath=======>');
    }
    public void Tackbreakfast() {
        System.debug ('Tackbreakfast=======>');
    }
    public void Carservice() {
        System.debug ('Carservice=======>');

    }
    public void GotoOffice() {
        System.debug ('GotoOffice=======>');

    }
}
